# Generated by Django 4.0.4 on 2022-08-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docid', models.EmailField(max_length=254)),
                ('docname', models.EmailField(max_length=70)),
                ('docloc', models.EmailField(max_length=100)),
                ('tags', models.CharField(max_length=70)),
            ],
        ),
    ]
